/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Cascader: typeof import('./src/components/Problem/Cascader.vue')['default']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    MonacoEditor: typeof import('./src/components/Problem/MonacoEditor.vue')['default']
    NavBar: typeof import('./src/components/Home/NavBar.vue')['default']
    ProblemTable: typeof import('./src/components/Problem/ProblemTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectDown: typeof import('./src/components/User/SelectDown.vue')['default']
  }
}
